### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by dsciamma**
test

### CODE REVIEW

**Comment by dsciamma** [comment]
toto

**Comment by dsciamma** [comment]
test2

**Comment by dsciamma** [comment]
test2

**Comment by dsciamma** [comment]
Here is the checklist to complete before merging pull request:
- [ ] Branch is up-to-date (master merged into it)
- [ ] Code review done
- [ ] Translation done (if required)
- [ ] Non-regression tests updated
- [ ] Documentation updated (API, N&N)
- [ ] Performance tests done
- [ ] Smoke tests reviewed
- [ ] Feature validated
- [ ] Smoke tests OK
- [ ] Non-regression tests OK (put the list of non-regression tests done)
- [ ] Jasmine tests written (if required)

**Comment by dsciamma** [comment]
Here is the checklist to complete before merging pull request:
- [ ] Branch is up-to-date (master merged into it)
- [ ] Code review done
- [ ] Translation done (if required)
- [ ] Non-regression tests updated
- [ ] Documentation updated (API, N&N)
- [ ] Performance tests done
- [ ] Smoke tests reviewed
- [ ] Feature validated
- [ ] Smoke tests OK
- [ ] Non-regression tests OK (put the list of non-regression tests done)
- [ ] Jasmine tests written (if required)

**Comment by airvantage-cop** [comment]
Here is the checklist to complete before merging pull request:
- [ ] Branch is up-to-date (master merged into it)
- [ ] Code review done
- [ ] Translation done (if required)
- [ ] Non-regression tests updated
- [ ] Documentation updated (API, N&N)
- [ ] Performance tests done
- [ ] Smoke tests reviewed
- [ ] Feature validated
- [ ] Smoke tests OK
- [ ] Non-regression tests OK (put the list of non-regression tests done)
- [ ] Jasmine tests written (if required)

Don't hesitate to modify/complete this list. We just need to trace what was done and how.

**Pull request closed without merging**
